application: bmorejs
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  
- url: /static
  static_dir: static
  
- url: /api/.*
  script: api.py
  
- url: /
  static_files: index.html
  upload: index.html